blank_issues_enabled: true
contact_links:
  - name: Community Support (Discord)
    url: https://discord.gg/YkBj8hMfqz
    about: For general questions, please use our community Discord (link in README).
